version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - dupl
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace
    - errorlint
    - errname

run:
  timeout: 5m
  go: '1.25'
