version: 2

run:
  timeout: 5m
  go: '1.25'

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - dupl
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace
    - errorlint
    - errname

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    rules:
      - name: exported
      - name: package-comments
      - name: var-naming

  gosec:
    excludes:
      - G404

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

  max-issues-per-linter: 0
  max-same-issues: 0
